name: Rewards Action

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          

      - name: download
        run: |
           wget "$(echo '${{ secrets.ACTIVE }}')" -O MicrosoftRewardsBot.py > /dev/null 2>&1
           echo " key verified! Download complete."

          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Main ID
        run: |
          python MicrosoftRewardsBot.py --headless --fast --emailalerts --accounts "${{ secrets.FIRST }}"
      - name: Collect logs
        uses: actions/upload-artifact@v3
        with:
           name: logs
           path: logs.txt

      - name: Concatenate logs
        run: |
            for i in {1..10}; do
            if [ -f "logs.txt" ]; then
            cat "logs.txt" >> all_logs.txt
            fi
            done
      - name: upload to tele via api
        continue-on-error: true
        run: |
         curl -F document=@all_logs.txt -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument

      
      
      
      
      
      
      
